# Dependabot configuration for automated dependency management
version: 2

updates:
  # NPM package management
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "repository-owner"
    assignees:
      - "repository-owner"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group security updates for immediate attention
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
      major-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-major"
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    # Ignore specific packages that require manual updates
    ignore:
      # Ignore major Next.js updates (require manual testing)
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      # Ignore major React updates
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      # Ignore major TypeScript updates (may break builds)
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    # Enable automatic security updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Increase versioning strategy for better compatibility
    versioning-strategy: "increase"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "repository-owner"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
    groups:
      actions-updates:
        patterns:
          - "*"

  # Docker updates (if Dockerfile exists)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "repository-owner"
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "docker"
      - "automated"